#!/usr/bin/env php

<?php

$readme = file_get_contents(__DIR__.'/../../README.md');
preg_match_all('~\'([a-f0-9]{96})\'~', $readme, $regexResults);

$shaOfInstaller = hash_file('SHA384', __DIR__.'/../../installer.php');

if (count($regexResults[1]) === 0) {
    echo <<<ERROR
\e[31;31mNo SHA384 hash found in \e[31;33mREADME.md\e[31;31m. This means the installer won't be
(correctly) verified upon download, which is a security risk! For reference, the
current SHA384 hash of installer.php is:

    \e[31;33m$shaOfInstaller\e[31;31m
\e[0m

ERROR;
    exit(1);
}

if (count($regexResults[1]) > 1) {
    printf("\e[31;31mFound %d SHA384 hashes in README.md, expected only 1\e[0m\n", count($regexResults[1]));
    exit(1);
}

if ($shaOfInstaller !== $regexResults[1][0]) {
    echo <<<ERROR
\e[31;31m
The SHA384 hash of installer.php in README.md file is incorrect.
For reference, the current SHA384 hash of installer.php is:

    $shaOfInstaller
\e[0m

ERROR;

    exit(1);
}
