services:
    qa_tools.tool.configurator.phpunit:
        class: Ibuildings\QaTools\Tool\PhpUnit\Configurator\PhpUnitConfigurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.sf2'
            - name: qa_tools.tool
              project_type: 'php.sf3'
            - name: qa_tools.tool
              project_type: 'php.drupal7'
            - name: qa_tools.tool
              project_type: 'php.drupal8'
            - name: qa_tools.tool
              project_type: 'php.other'
