sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
addons:
    apt:
        packages: [expect]

cache:
  directories:
    - ~/.composer/cache/files/

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --prefer-dist

script:
  - make test

after_success:
    # Deploy documentation to gh-pages branch when Travis CI build against PHP 7.1 on master succeeds
  - GIT_NAME=TravisCI GIT_EMAIL=info@ibuildings.nl GH_REF=github.com/ibuildingsnl/qa-tools-v3 vendor/bin/couscous travis-auto-deploy --php-version=7.1

branches:
  only: [master, develop]
