sudo: false
language: php
php:
  - 5.6
  - 7.0
  - nightly

cache:
  directories:
    - ~/.composer/cache/files/

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --prefer-dist

before_script:
  # Ancient make binary at TravisCI doesn't support indentation with spaces
  - unexpand -t 4 Makefile > Makefile.tmp && mv Makefile.tmp Makefile
  # Increase open file limit
  # See https://github.com/box-project/box2/issues/80#issuecomment-76630852
  - ulimit -Sn 4096

script:
  - make build

branches:
  only: [master, develop]
