sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
addons:
    apt:
        packages: [expect]

cache:
  directories:
    - ~/.composer/cache/files/

before_install:
  - phpenv config-add .travis.php.ini

install:
  - composer install --prefer-dist

before_script:
  - make generate-test-signing-key

script:
  - make test

branches:
  only: [master, develop]
