services:
    qa_tools.tool.configurator.behat:
        class: Ibuildings\QaTools\Tool\Behat\Configurator\BehatConfigurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.sf2'
            - name: qa_tools.tool
              project_type: 'php.sf3'
            - name: qa_tools.tool
              project_type: 'php.other'

    qa_tools.tool.configurator.behat.drupal:
        class: Ibuildings\QaTools\Tool\Behat\Configurator\BehatConfigurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.drupal7'
            - name: qa_tools.tool
              project_type: 'php.drupal8'
