services:

    qa_tools.tool.configurator.php_parallel_lint.php:
        class: Ibuildings\QaTools\Tool\PhpParallelLint\Configurator\PhpParallelLintConfigurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.sf2'
            - name: qa_tools.tool
              project_type: 'php.sf3'
            - name: qa_tools.tool
              project_type: 'php.other'

    qa_tools.tool.configurator.php_parallel_lint.php_drupal:
        class: Ibuildings\QaTools\Tool\PhpParallelLint\Configurator\DrupalPhpParallelLintConfigurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.drupal7'
            - name: qa_tools.tool
              project_type: 'php.drupal8'
