#!/usr/bin/env bash

# Absolute path to this script, e.g. /path/to/pre-commit.bash
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /path/to
SCRIPTPATH=$(dirname "$SCRIPT")

(cd $SCRIPTPATH/../.. && make test-fast)
