services:

    qa_tools.tool.configurator.phpmd.php:
        class: Ibuildings\QaTools\Tool\PhpMd\Configurator\PhpMdConfigurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.sf2'
            - name: qa_tools.tool
              project_type: 'php.sf3'
            - name: qa_tools.tool
              project_type: 'php.other'

    qa_tools.tool.configurator.phpmd.php_drupal:
        class: Ibuildings\QaTools\Tool\PhpMd\Configurator\DrupalPhpMdConfigurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.drupal7'
            - name: qa_tools.tool
              project_type: 'php.drupal8'
