services:
    qa_tools.tool.phpmd:
        class: Ibuildings\QaTools\Tool\PhpMd\Configurator\PhpMdSf2Configurator
        tags:
            - name: qa_tools.tool
              project_type: 'php.sf2'
