parameters:
    qa_tools.configuration_location: "./qa-tools.json"

    qa_tools.ant_template_location: "%application_root_dir%/src/Core/Resources/templates"

    qa_tools.ant.tool_priorities: ["phplint", "phpcs", "phpmd"]
