services:
    file_handler:
        alias: qa_tools.io.file.filesystem_adapter

    qa_tools.interviewer_factory:
        alias: qa_tools.io.cli.interviewer_factory

    qa_tools.project_configurator:
        alias: qa_tools.project.project_configurator

    qa_tools.run_list:
        alias: qa_tools.configurator.run_list

    qa_tools.configuration_builder.factory:
        class: Ibuildings\QaTools\Core\ConfigurationBuilder\ConfigurationBuilderFactory

    qa_tools.configurator.run_list:
        class: Ibuildings\QaTools\Core\Configurator\RunList

    qa_tools.io.file.filesystem_adapter:
        class: Ibuildings\QaTools\Core\IO\File\FilesystemAdapter
        arguments:
            - "@symfony.filesystem"

    qa_tools.io.cli.console_question_factory:
        class: Ibuildings\QaTools\Core\IO\Cli\ConsoleQuestionFactory
        arguments:
         - "@qa_tools.io.cli.console_question_formatter"

    qa_tools.io.cli.console_question_formatter:
        class: Ibuildings\QaTools\Core\IO\Cli\ConsoleQuestionFormatter

    qa_tools.io.cli.interviewer_factory:
        class: Ibuildings\QaTools\Core\IO\Cli\InterviewerFactory
        arguments:
            - "@file_handler"
            - "@symfony.question_helper"
            - "@qa_tools.io.cli.console_question_factory"

    qa_tools.project.project_configurator:
        class: Ibuildings\QaTools\Core\Project\ProjectConfigurator
        arguments:
            - "@qa_tools.io.cli.interviewer_factory"

    symfony.filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    symfony.question_helper:
        class: Symfony\Component\Console\Helper\QuestionHelper

    symfony.formatter_helper:
        class: Symfony\Component\Console\Helper\FormatterHelper
