services:
    qa_tools.task.install_composer_dev_dependency_task_executor:
        class: Ibuildings\QaTools\Core\Task\Executor\InstallComposerDevDependencyTaskExecutor
        arguments:
            - "@qa_tools.composer.project_factory"
        tags: [{ name: qa_tools.task_executor, priority: 10 }]

    qa_tools.task.write_file_task_executor:
        class: Ibuildings\QaTools\Core\Task\Executor\WriteFileTaskExecutor
        arguments:
            - "@qa_tools.file_handler"
        tags: [{ name: qa_tools.task_executor, priority: 0 }]

    qa_tools.task.add_build_task_executor:
        class: Ibuildings\QaTools\Core\Task\Executor\AddBuildTaskExecutor
        arguments:
            - "@qa_tools.file_handler"
            - "@qa_tools.template_engine"
            - "%qa_tools.ant_template_location%"
        tags: [{ name: qa_tools.task_executor, priority: 5 }]
